language: node_js
node_js:
  - "node"
before_script:
  - npm install -g markdownlint-cli
  - npm install -g markdown-link-check
  - npm install -g gitbook-cli
  - chmod +x scripts/Apply_Linter_Check.sh
  - chmod +x scripts/Generate_Site.sh
  - python --version
  - python3 --version  
script:
  - ls -l
  - echo "Apply linter check..."
  - cd scripts; bash Apply_Linter_Check.sh
  - echo "Try to generate the offline website..."
  - sed -i 's/python/python3/g' scripts/Generate_Site.sh
  - cd scripts; bash Generate_Site.sh
  - ls -l generated/site/