version: 2
jobs:
  build-offline-website:
    docker:
      - image: 'circleci/node:10-stretch'
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
    - checkout
    - run: 'sudo apt-get install -y python3.5'
    - run: 'sudo npm install -g markdownlint-cli'
    - run: 'sudo npm install -g markdown-link-check'
    - run: 'sudo npm install -g gitbook-cli'
    - run: 'chmod +x scripts/Apply_Linter_Check.sh'
    - run: 'chmod +x scripts/Generate_Site.sh'
    - run: 'sed -i "s/python/python3\.5/g" scripts/Generate_Site.sh'
    - run: 'cd scripts;bash Apply_Linter_Check.sh'
    - run: 'cd scripts;bash Generate_Site.sh'
    - run: 'ls -l generated/site/'
    - run: 'cd generated;zip -r ../site.zip site'
    - run: 'zip -T site.zip'
    - persist_to_workspace:    
        root: generated
        path: 
          - site
    - store_artifacts:
        path: ./site.zip
        destination: OfflineWebsite-NightBuild.zip
  deploy-offline-website:
    docker:
      - image: 'circleci/node:10-stretch'
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
    - checkout
    - run: 'git checkout gh-pages'
    - run: 'git branch'
    - attach_workspace:
        at: /tmp/workspace      
    - run: 'ls -l'    
    - run: 'ls -rtl /tmp/workspace'  
    - run: 'rm -rf assets 1>/dev/null 2>&1'
    - run: 'rm -rf cheatsheets 1>/dev/null 2>&1'
    - run: 'rm -rf gitbook 1>/dev/null 2>&1'
    - run: 'rm index.html 1>/dev/null 2>&1'
    - run: 'rm search_index.json 1>/dev/null 2>&1'
    - run: 'ls -l'    
    - run: 'cp -vr /tmp/workspace/site/assets .'
    - run: 'cp -vr /tmp/workspace/site/cheatsheets .'
    - run: 'cp -vr /tmp/workspace/site/gitbook .'
    - run: 'cp -v /tmp/workspace/site/index.html .'
    - run: 'cp -v /tmp/workspace/site/search_index.json .'
    - run: 'ls -l'
workflows:
  version: 2
  scheduled-night-deploy:
    jobs:
      - build-offline-website:
          filters:
            branches:
              only:
                - master      
      - deploy-offline-website:
          requires:
            - build-offline-website
          filters:
            branches:
              only:
                - master      
  scheduled-night-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-offline-website
