version: 2
jobs:
  build-offline-website:
    docker:
      - image: 'circleci/node:10-stretch'
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
    - checkout
    - run: 'sudo apt-get install -y python3.5'
    - run: 'sudo npm install -g markdownlint-cli'
    - run: 'sudo npm install -g markdown-link-check'
    - run: 'sudo npm install -g gitbook-cli'
    - run: 'chmod +x scripts/Apply_Linter_Check.sh'
    - run: 'chmod +x scripts/Generate_Site.sh'
    - run: 'sed -i "s/python/python3\.5/g" scripts/Generate_Site.sh'
    - run: 'cd scripts'
    - run: 'bash Generate_Site.sh'
    - run: 'cd ..'
    - run: 'ls -l generated/site/'
    - run: 'cd generated'
    - run: 'zip -r ../site.zip site'
    - run: 'zip -T site.zip'
    - store_artifacts:
        path: ./site.zip
        destination: OfflineWebsite-NightBuild.zip
workflows:
  version: 2
  git-push-build:
    jobs:
      - build-offline-website
  scheduled-night-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-offline-website
