version: 2
jobs:
  build-offline-website:
    docker:
      - image: 'circleci/node:10-stretch'
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
    - checkout
    - run: 'sudo apt-get install -y python3.5'
    - run: 'sudo npm install -g markdownlint-cli'
    - run: 'sudo npm install -g markdown-link-check'
    - run: 'sudo npm install -g gitbook-cli'
    - run: 'chmod +x scripts/Apply_Linter_Check.sh'
    - run: 'chmod +x scripts/Generate_Site.sh'
    - run: 'sed -i "s/python/python3\.5/g" scripts/Generate_Site.sh'
    - run: 'cd scripts;bash Apply_Linter_Check.sh'
    - run: 'cd scripts;bash Generate_Site.sh'
    - run: 'ls -l generated/site/'
    - run: 'cd generated;zip -r ../site.zip site'
    - run: 'zip -T site.zip'
    - store_artifacts:
        path: ./site.zip
        destination: OfflineWebsite-NightBuild.zip
  deploy-offline-website:
    docker:
      - image: 'circleci/node:10-stretch'
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
    - checkout
    - run: 'sudo apt-get install -y curl jq unzip wget zip'
    - run: 'git checkout gh-pages'
    - run: 'git branch'
    - run: 'tgt=`curl -s https://circleci.com/api/v1.1/project/github/OWASP/CheatSheetSeries/latest/artifacts | jq -r .[0].url` ; wget $tgt'
    - run: 'zip -T OfflineWebsite-NightBuild.zip'
    - run: 'unzip OfflineWebsite-NightBuild.zip'    
    - run: 'rm -rf assets 1>/dev/null 2>&1'
    - run: 'rm -rf cheatsheets 1>/dev/null 2>&1'
    - run: 'rm -rf gitbook 1>/dev/null 2>&1'
    - run: 'rm index.html 1>/dev/null 2>&1'
    - run: 'rm search_index.json 1>/dev/null 2>&1'
    - run: 'mv site/* .'
    - run: 'upd=`date +"%Y-%m-%d at %T"`; echo "Website last update: $upd." > README.md'
    - run: 'rm -rf site'
    - run: 'rm OfflineWebsite-NightBuild.zip'
    - run: 'ls -rtl assets'
    - run: 'ls -rtl cheatsheets'
    - run: 'ls -rtl gitbook'
    - run: 'ls -rtl'
    - run: 'git config --global user.email "OWASP-CheatSheetSeries@circleci.com"'
    - run: 'git config --global user.name "CircleCI-CheatSheetSeries"'
    - run: 'git add --all .'
    - run: 'git commit -a -m "Deploy the generated website via CircleCI pipeline."'
    - run: 'git push'
workflows:
  version: 2
  build-release-deploy:
    jobs:
      - build-offline-website:
          filters:
            branches:
              only:
                - master      
      - deploy-offline-website:
          requires:
            - build-offline-website
          filters:
            branches:
              only:
                - master      
  scheduled-night-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-offline-website
